#!/bin/sh
# leg20170215:
#
# Bootstrap build system from distclean (to avoid typing) first
# argument on commandline is used as --prefix and --exec-prefix
# argument for ./configure.  The rest of the arguments is passed
# directly.

PREFIX=${1:-/opt/tcl}

if [ -n "$1" ]; then
    shift
fi

# autoheader checks if we want stubs.  Stubs do not work for now, so
# we just use autoconf with a pre-compiled and manually modified
# config.h.in

# autoheader

autoconf
./configure --prefix=$PREFIX --exec-prefix=$PREFIX "$@"
