/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#if !defined(__WIN32__) && !defined(_WIN32)
#include <sys/time.h>
#endif
#include "rstat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

statstime *
rstatproc_stats_3(void *argp, CLIENT *clnt)
{
	static statstime res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statstime, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

u_int *
rstatproc_havedisk_3(void *argp, CLIENT *clnt)
{
	static u_int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

statsswtch *
rstatproc_stats_2(void *argp, CLIENT *clnt)
{
	static statsswtch res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statsswtch, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

u_int *
rstatproc_havedisk_2(void *argp, CLIENT *clnt)
{
	static u_int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

stats *
rstatproc_stats_1(void *argp, CLIENT *clnt)
{
	static stats res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_stats, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

u_int *
rstatproc_havedisk_1(void *argp, CLIENT *clnt)
{
	static u_int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

