/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rstat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

statstime *
rstatproc_stats_3(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statstime clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_statstime, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_3(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_u_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

statsswtch *
rstatproc_stats_2(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statsswtch clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_statsswtch, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_2(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_u_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

stats *
rstatproc_stats_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static stats clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_stats, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_u_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
