#!/bin/sh
# leg20170215:
#
# Bootstrap build system from distclean (to avoid typing) first
# argument on commandline is used as --prefix and --exec-prefix
# argument for ./configure.  The rest of the arguments is passed
# directly.

echo "You may wish to just run 'autoreconf' with your favorite flags instead of running this script."

PREFIX=${1:-/opt/tcl}

if [ -n "$1" ]; then
    shift
fi

set -ex;

autoheader -Wno-obsolete
autoconf -Wno-obsolete
./configure --prefix="$PREFIX" --exec-prefix="$PREFIX" "$@"
